# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: c2938aaa9489862bf0f2d7b0240a4c0121c243099254121ef2d8d501618ea1053a3c3627c5fb3bed0b9da71c4bb4312de922e492a4f26f040979725075b3b0ef

test:
  secret_key_base: c1bd5f474b884b0ab39894d356fbafeefff08ab5177376fea86680a0dc86dbeae58805ced22dd42b6230653a088aa8ce161c3f11725016fb8f70d9fb2a45134a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
